### ISSUE TITLE
关于BERT与MLM

### ISSUE THREAD

**Issue by TianqiFu** [HITSZ-HLT/SPT-ABSA#1]
想请教在实验中基线BERT与MLM有何区别，BERT与MLM是使用不同的掩码策略吗？

**Comment by 1140310118** [comment]
你好。MLM是指使用掩码语言建模的目标对BERT进行进一步的预训练，这里的预训练语料为laptop和restaurant领域的评论。

**Comment by TianqiFu** [comment]
感谢回复。我能否这样理解，实验中的基线BERT是用了BERT-base-uncased的初始权重，而MLM是在此基础上使用随机15%的掩码策略利用laptop和restaurant领域的评论进一步的训练？

**Comment by 1140310118** [comment]
是的。

**Comment by TianqiFu** [comment]
谢谢！
